# Generated by Django 2.1.7 on 2019-03-03 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('update', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='printer',
            name='prev_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
